### ISSUE TITLE
Testrunner shows up with ORA-12154

### ISSUE THREAD

**Issue by rkelterer** [utPLSQL/utPLSQL-PLSQL-Developer#15]
Hi,

after installing the dll and creating a test, which I can execute successfully from the commandline, I tried to press the "Run all tests from current user" then I am getting an ORA-12154. The same error shows up when I try to run the test from the "Objects" window with right click and select "Run utPLSQL Test". Die I miss a configuration step ?

kind regards
Raimund

**Comment by simasch** [comment]
Hi Raimund,

What Oracle Client are you using?

If you have Oracle XE installed locally did you set TNS_ADMIN as environment variable?

Thanks, Simon

**Comment by rkelterer** [comment]
Hi Simon,

I use the automatic detection and the plsql-developer in multi session mode. The database is a 12.1.0.1. standard edition. 
I set my installed 11g client explicitly - but  no change in error message.

kind regards
Raimund

**Comment by simasch** [comment]
Can you please set the TNS_ADMIN environment variable and point it to the directory where your tnsnames.ora is:

https://docs.oracle.com/en/database/oracle/oracle-database/19/ntqrf/about-tns-admin-parameter.html#GUID-7EE1F936-F108-4575-941C-63E0011B0CC0

**Comment by rkelterer** [comment]
I set TNS_ADMIN and started SQLDeveloper and now then GUI shows up the Tests.

Thanks and best wishes from Austria
Raimund

**Comment by simasch** [comment]
Great that it works!

**Comment by rkelterer** [comment]
It looks like that PlsqlDeveloper takes the information from the registry [HKLM\Software\Oracle] together with the "Oracle_Home" from properties to setup the TNS configuration. The plugin does that only over the environment.

Thanks again for fast response
Raimund

**Comment by simasch** [comment]
That's indeed strange.
I'm using the Oracle .NET managed client and this obviously  needs the TNS_ADMIN or ORACLE_HOME environment variable.
