### ISSUE TITLE
TNS couldnt resolve the connect identifier spoecified

### ISSUE THREAD

**Issue by Alesator** [utPLSQL/utPLSQL-PLSQL-Developer#17]
Hi,
when I try to run tests from PL/SQL Developer, it immediately fails with error ORA-12154: TNS couldnt resolve the connect identifier spoecified.
The problem occurs when I use external tnsnames.ora, which is parametrized in local tnsnames by IFILE=T:\TNS_ADMIN\tnsnames.ora.

When I use local tnsnames.ora, then it is OK (probably)

**Comment by simasch** [comment]
Hi,

Have you set TNS_ADMIN or ORACLE_HOME?

Thanks, Simon

**Comment by Alesator** [comment]
yes, sure ... but the inctance is in the external tnsnames.ora ... 

My environment looks like this:
C:\Users\arychtera>set tns
TNS_ADMIN=C:\TNS_ADMIN

C:\TNS_ADMIN\tnsnames.ora:
TSDV1_LOCAL=                                              (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=suntest07.cpoj.cz)(PORT=1530))(CONNECT_DATA=(SERVICE_NAME=TSDV1)))

**IFILE=T:\TNS_ADMIN\tnsnames.ora**

And in T:\TNS_ADMIN\tnsnames.ora there is my instance with alias TSDV3 ...
TSDV3=                                           (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=czstiavyvtt.cpas.cz)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ORCL)))

And it is not visible to utplsql plugin ... other connections from i.e.. sql*plus, pl/sql developer and so on is worknig properly

**Comment by simasch** [comment]
The utPLSQL Plugin is using ODP .NET Managed Client from Oracle and this driver does not support IFILE in tnsnames.ora yet.
I don't know if Oracle is planning to add support for this in the future.
