### ISSUE TITLE
"Connect failed" error

### ISSUE THREAD

**Issue by ukropini** [utPLSQL/utPLSQL-PLSQL-Developer#18]
Getting "Connect failed" (ORA-12154: TNS:could not resolve the connect identifier specified) error while trying to run any test (after clicking any menu item).
I have an impression that this plugin ignores **TNS_ADMIN** variable because adding the **tnsnames.ora** file into $ORACLE_HOME/NETWORK/ADMIN directory has resolved this problem.
It would be nice if this plugin could support the **TNS_ADMIN** variable.

Also I can't find some components in the sources (e.g. RealTimeTestRunner, FontAwesome.Sharp) and can't build a solution.

**Comment by simasch** [comment]
Hi,

The plugin uses the offical Oracle Data Provider for .NET. I will check if TNS_ADMIN is not supported by this driver.

The mentioned dependencies are NuGet package. You have to restore them. Read more about this here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-packages-automatically-using-visual-studio
