### ISSUE TITLE
Symantec Endpoint Protection moves plug-in to quarantine

### ISSUE THREAD

**Issue by druvissiksalietis** [utPLSQL/utPLSQL-PLSQL-Developer#19]
In the last days plugin is moved to the quarantine and it is no more working.
Even a new download from GitHub asap is quarantined.
Does Github host an infected version?

![Capture](https://user-images.githubusercontent.com/80620706/111063510-a52cf280-84b7-11eb-9141-33265ca72267.PNG)

**Comment by simasch** [comment]
Hi,

That must be a false positive of Symantec. I can't see the reason why it is considering that as malware.
The version is not infected and all other virus scanner do not complain.

Do you see any reason why Symantec tells you that it's malware?

Thanks, Simon

**Comment by druvissiksalietis** [comment]
According to the article https://community.norton.com/en/forums/clarification-wsreputation1-detection, the developer can submit a dispute.

**Comment by simasch** [comment]
I will try to add the plugin to the whitelist.
Thanks.
