### ISSUE TITLE
Install plug-In PLSQL Developer

### ISSUE THREAD

**Issue by alexzab1973** [utPLSQL/utPLSQL-PLSQL-Developer#20]
Hi, Simon!
I try install plug-in ver 1.2.3 for PLSQL Developer ver 11 - error in attach.
What wrong?
Can you help me?
![ErrUt](https://user-images.githubusercontent.com/83286882/118828449-f4cbd800-b8c5-11eb-8b87-db928f399889.png)

**Comment by simasch** [comment]
The plug-in is tested on the most recent version 14.
Why are you using version 11?

**Comment by alexzab1973** [comment]
Thank you very match for answer!!!!!
