### ISSUE TITLE
Manually enter path in run window

### ISSUE THREAD

**Issue by compubasejovl** [utPLSQL/utPLSQL-PLSQL-Developer#21]
It would be nice if it was possible to manually enter the path to run, and that the path entry accept the same entry as the procedure  ut.run() does. 
So that you could enter either the package, the test procedure or you could use the suitepath or part of it.

**Comment by simasch** [comment]
@compubasejovl Why do you need that because you can go to the objects browser and start the tests from there.

**Comment by compubasejovl** [comment]
@simasch, thanks for you reply. 

The reason is so that we could run all test from a specific suitepath. For example we have a test package with the following suitepath, "cce.tables.cce_gbr_klt_data_autorisatie.business_rules.cer0193". I know that it is possible to run part of the path, so we could run al test from "cce.tables.cce_gbr_klt_data_autorisatie" or "cce.tables", this is possible if we run the tests from plsql directly. 

It would be nice to have that option in de plsql-developer plugin also, if I run the package with the suitepath from above the plugin shows the path "cce.tables.cce_gbr_klt_data_autorisatie.business_rules.cer0193", but I cannot alter is so that the plugin runs all test from "cce.tables"

I hope that it's clear why we want to have that option, if you have any questions let me know.

**Comment by simasch** [comment]
@compubasejovl Now it's clear. Thank you

**Comment by simasch** [comment]
@compubasejovl There is new release https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/releases/tag/1.2.4
Would you please be so kind and test it if it fits your expectations? 
If not please feel free to reopen the issue.
Thank you

**Comment by compubasejovl** [comment]
@simasch, thanks for the enhancement. It's exactly what I asked for.

**Comment by simasch** [comment]
@compubasejovl Great Thanks for the feedback!

**Comment by jgebal** [comment]
@simasch 
I can't find a mention of that feature in documentation (readme).
Can you add a screenshot and few words to describe that it's available and how to use it?
