### ISSUE TITLE
Update for Pl/SQL Developer 15

### ISSUE THREAD

**Issue by jeffcino** [utPLSQL/utPLSQL-PLSQL-Developer#26]
Are you going to have a update for version 15 when it comes out soon.  Currently it doesn't work in the Beta version

**Comment by simasch** [comment]
What does not work for you?
Besides a few visual imperfections everything still works.

**Comment by jeffcino** [comment]
Sorry never mind. I didn't realize I needed to upgrade utplsql to version 3.1.4 or above.  It is working now.
Thanks
