### ISSUE TITLE
Installation of plugin in 32-bit version of PL/SQL Developer

### ISSUE THREAD

**Issue by PhilippSalvisberg** [utPLSQL/utPLSQL-PLSQL-Developer#3]
I tried to installed it on  my machine. I copied the downloaded `PlsqlDeveloperUtPlsqlPlugin.dll` in the following directories:

- `C:\Program Files (x86)\PLSQL Developer 13\PlugIns`
- `C:\Program Files (x86)\PLSQL Developer 14\PlugIns`

Afterwards I started PL/SQL Developer version 13.0.6.1911 and 14.0.3.1981. But the plugin was not loaded. No context menu, no utPLSQL Icon in the Plug-Ins section.

I use 32-bit bit versions of PL/SQL Developer. I assume the DLL requires a 64-bit architecture. Any chance to make the plugin available also as 32-bit version?

**Comment by simasch** [comment]
I'm sorry but I forgot about 32bit.

I've added a 32bit version to the release: 
 https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/releases/tag/0.1.0

**Comment by PhilippSalvisberg** [comment]
Wow. That was fast. I can confirm that it works in my 32-bit installations! Thanks a lot.
