### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by jtsoya539** [utPLSQL/utPLSQL-PLSQL-Developer#8]
Plug-In installed correctly but test results window not showing up

PL/SQL Developer Version 14.0.0.1961 (64 bit)
utPLSQL v3.1.10.3349
Plug-In Version 1.1.0

**Comment by simasch** [comment]
Can you please start plsqldev.exe with debug:

`plsqldev.exe DebugPlugins`

And then post the Debug.txt file that is located here:
"c:\Users\<your-username>\AppData\Roaming\PLSQL Developer 14\Debug.txt"

**Comment by jtsoya539** [comment]
I pressed _**Tools > Run all tests of current user**_ three times.. nothing happened.

Here is the Debug.txt file:
[Debug.txt](https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/files/5791396/Debug.txt)

**Comment by simasch** [comment]
And you are connected to the database in PL/SQL Developer?

**Comment by jtsoya539** [comment]
Sure.
This is the result when running `BEGIN ut.run(); END;`

![Captura de pantalla 2021-01-09 134459](https://user-images.githubusercontent.com/19676105/104103442-e5d27a80-5280-11eb-9e70-f5872900f8c4.png)

Just let me know if I can help you in some way
Thanks!

**Comment by simasch** [comment]
Can you go to the package k_dato in the objects browser and try to run the tests from the context menu, please?

**Comment by jtsoya539** [comment]
nothing happens either :(

[Debug.txt](https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/files/5791448/Debug.txt)

**Comment by simasch** [comment]
I would like to provide a debug version for you. Are you using the 32bit or 64bit version?

**Comment by jtsoya539** [comment]
64bit version

**Comment by simasch** [comment]
Can you please try with this version: https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/releases/tag/1.1.1.RC1

Thank you

**Comment by jtsoya539** [comment]
Sorry, same behavior

When I'm not connected I get this error:
![Captura de pantalla 2021-01-09 141759](https://user-images.githubusercontent.com/19676105/104104217-82971700-5285-11eb-843f-308ab341eaae.png)

But, when I'm connected nothing happens

[Debug.txt](https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/files/5791478/Debug.txt)

**Comment by simasch** [comment]
Ok. I will have to try to reproduce the problem.
As I can see in the logfile you are using Oracle XE 18c.

**Comment by jtsoya539** [comment]
Yes, Oracle XE 18c

Ok. Thanks in advance!

**Comment by simasch** [comment]
Hi @jtsoya539 
which Windows version are you running?

And can you please install https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/releases/tag/1.1.1.RC2 and send me a screenshot if there is a error dialog shown?

Thank you

**Comment by jtsoya539** [comment]
Hi @simasch 

I'm running Windows 10 Home 20H2 Build 19042.685

Sorry, no error dialog shown:
![FVfVYKrVSN](https://user-images.githubusercontent.com/19676105/104130614-7c21a180-5350-11eb-969b-ae02f39d62ef.gif)

**Comment by simasch** [comment]
That's very strange! I installed risk and I can run all the tests.

I've a standalone version attached. Can you try to run this and tell me what happens?
Make sure that ORACLE_HOME is set before you run the app.

[utPLSQL.UI.Standalone.zip](https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/files/5793053/utPLSQL.UI.Standalone.zip)

**Comment by jtsoya539** [comment]
It's working now!
![image](https://user-images.githubusercontent.com/19676105/104132514-7e89f880-535c-11eb-926a-da4f17972c22.png)

Apparently, the problem is caused by ORACLE_HOME environment variable not defined.

**Comment by simasch** [comment]
Thanks for letting me know.

I will close this issue and open a new one. The plugin should use the Oracle Home used by PL/SQL Developer.

**Comment by simasch** [comment]
Will be fixed with https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/issues/9

**Comment by jtsoya539** [comment]
@simasch Thanks for your support and for this great Plug-In!

I appreciate your work
Cheers!

**Comment by simasch** [comment]
@jtsoya539 I just release a new version:
https://github.com/utPLSQL/utPLSQL-PLSQL-Developer/releases/tag/1.1.1

Now you don't need to set ORACLE_HOME env variable.

**Comment by jtsoya539** [comment]
Solved!
